### ISSUE TITLE
`Not supported in the v1/completions endpoint` when use the default gpt-4 model

### ISSUE THREAD

**Issue by huihuaNvidia** [ut-amrl/codebotler#12]
I pulled the code and setup the environment as instructed. I could run the `codebotler.py` successfully with the webpage.

However, when I click generate, the following error shows up
```
(codebotler) hh@hh:~/repos/codebotler$ python3 codebotler.py 
Could not import rospy. Robot interface is not available.
Using OpenAI model: gpt-4
Starting server at http://localhost:8080
127.0.0.1 - - [06/Dec/2023 16:05:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Dec/2023 16:05:14] "GET /favicon.ico HTTP/1.1" 200 -
Received code generation request
connection handler failed
Traceback (most recent call last):
  File "/home/hh/.local/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/home/hh/.local/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/home/hh/repos/codebotler/codebotler.py", line 128, in ws_main
    await handle_message(websocket, message)
  File "/home/hh/repos/codebotler/codebotler.py", line 108, in handle_message
    code = generate_code(data["prompt"])
  File "/home/hh/repos/codebotler/codebotler.py", line 69, in generate_code
    code = model.generate_one(
  File "/home/hh/repos/codebotler/models/OpenAIModel.py", line 95, in generate_one
    return self.openai.Completion.create(**kwargs)["choices"][0]["text"]
  File "/home/hh/.local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/hh/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 115, in create
    response, _, api_key = requestor.request(
  File "/home/hh/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 181, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/hh/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 396, in _interpret_response
    self._interpret_response_line(
  File "/home/hh/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 429, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

```

Googling around little bit, it seems that the API is outdated if use the `gpt-4` model name. If I switch to `text-davinci-003`, everything works fine.

**Comment by OAHC2022** [comment]
@huihuaNvidia Hello Huihua, thank you for highlighting this matter. It appears that there have been significant changes to the openai package. Previously, version 0.27.8 was compatible. I've now revised the environment installation guidelines, which you can find [here](https://github.com/ut-amrl/codebotler#Requirements). Going forward, I plan to update the codebase to accommodate the latest versions of the openai package.
